import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import ResumePopupProvider from "@/components/contextProviders/resumePopupProvider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div className="z-50">
                    <Toaster
                        toastOptions={{
                            success: {
                                duration: 3000,
                            },
                            error: {
                                duration: 4000,
                            },
                        }}
                    />
                </div>
                <ResumePopupProvider>
                    <Header />
                    {children}
                </ResumePopupProvider>
            </body>
        </html>
    );
}
