import RootContextProvider from '@/components/contextProviders/rootContextProvider';
import type { Metadata } from 'next';
import { Toaster } from 'react-hot-toast';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <RootContextProvider>
                    <div className="z-50">
                        <Toaster
                            toastOptions={{
                                success: {
                                    duration: 3000,
                                },
                                error: {
                                    duration: 4000,
                                },
                            }}
                        />
                    </div>
                    {children}
                </RootContextProvider>
            </body>
        </html>
    );
}
