import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import ResumePopupProvider from "@/components/contextProviders/resumePopupProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <ResumePopupProvider>
                    <Header />
                    {children}
                </ResumePopupProvider>
            </body>
        </html>
    );
}
