services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    depends_on:
      - api
      - frontend
    ports:
      - "3000:3000"
      - "5000:5000"
  
  api:
    build:
      context: .
      dockerfile: Dockerfile 
    volumes:
      - ../API:/workspace/API:cached 
    working_dir: /workspace/API
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile 
    volumes:
      - ../frontend:/workspace/frontend:cached 
    working_dir: /workspace/frontend
