apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    nodePort: 31000
  selector:
    app: nextjs
